### ISSUE TITLE
No ParallaxEffect when using Fragments that extends SlideFragment

### ISSUE THREAD

**Issue by CeJienAJPC** [HeinrichReimer/material-intro#107]
Am I allowed to use Parallax animation when using Fragment slides that extend SlideFragment?

Initially, when my Fragment slides extended Fragment (from Android.app), I have to replace

` addSlide(new FragmentSlide.Builder()
                .fragment(FragmentChooseLanguage.newInstance())`

with

` addSlide(new FragmentSlide.Builder()
                .fragment(R.layout.fragment_choose_language)`

and the Parallax animation worked fine. Since I wasn't able to play with ClickListeners in the latter case, I started using fragment slides extending SlideFragment. But since then the Parallax animation isn't working at all. Am I missing something???

Regards

**Comment by HeinrichReimer** [comment]
Yeah, you have to manually add the parallax effect to custom slides for now. Look at the source code of `ParallaxFragment` and just copy the implementation.
It would also be great if you create a pull request where you edit `SlideFragment` to extend from `ParallaxFragment` rather than from `Fragment`. That way every `SlideFragment` would have parallax support too.
