### ISSUE TITLE
Question: Gradle does not sync Material Intro App

### ISSUE THREAD

**Issue by searchy2** [HeinrichReimer/material-intro#108]
Hi! :wave: 
Great library and I apologize for asking such a stupid question, how do you run the sample app? I cannot get Gradle to sync because of this error:

```
Error:Could not find com.google.firebase:firebase-core:9.0.0.
Required by:
    material-intro:app:unspecified
```

Image for reference: http://imgur.com/qAvuIOK

Thank you for your help!~ :up:

**Comment by HeinrichReimer** [comment]
Well, it seems like you cloned the repository  and now the dependencies of the sample app fail to be resolved.
The easiest solution would be to include the library via Gradle dependency rather than cloning the project.
If you still need to clone the library, you can delete the sample module.
The dependency missing is actually just Google Firebase so if you just remove the Firebase dependency from build.gradle that should be fine too.

**Comment by searchy2** [comment]
Yes, you are correct. Unfortunately, just removing the Firebase dependency does not resolve the problem. I am going to close this issue as my question has been answered but the issue persists. Thank you for the reply!
