### ISSUE TITLE
Executing async task when pressing right arrow

### ISSUE THREAD

**Issue by odin-** [HeinrichReimer/material-intro#178]
Hi,

I have a use case as follows: I am using the slides to let the user register in my app. I.e. I ask for login, email, and other user data.

One slide looks as follows:
1. The user inputs the email address in a TextInputEditText.
2. When pressing the right arrow I want to start a task to connect to the server and validate the address.

Is this a bad use for material-intro?

To facilitate this I would want to be able to let the user press the right arrow without signaling "not possible"-animation of the button. I then launch an async task and then when task is done I would like to either continue to next slide OR signal error (toast) and animation.

Would this be possible with the current code base? If not I will look into modifying your code. I guess this is a very specific use case you might not want to have in the mainline?

**Comment by daniel-stoneuk** [comment]
I do this in my app [Monitor](https://play.google.com/store/apps/details?id=com.danielstone.energyhive) (except with login instead) so it is certainly possible, although the "not possible" animation is shown I indicate loading with a TextView and simply move to the next slide when it has been validated. If you'd like me to share how I've done this just ask.

**Comment by odin-** [comment]
Please do share implementation details.

**Comment by HeinrichReimer** [comment]
The simplest solution for this would be to make use of a `NavigationPolicy`.
So here's a very basic scenario when using the `NavigationPolicy` to check a locally stored flag (possibly in shared prefs).
1. Block navigation for that specific slide in your navigation policy because the *registered*-flag is not set.
2. When the user clicks next on this slide you get a notification using an `OnNavigationBlockedListener`. Catch the _first_ click on next and start the registration task in background. If the task is already running do nothing.
4. Update your fragment UI.
3. When the task finishes set the *registered*-flag `true`. Notify the intro that your navigation policy return has changed.
4. Update your fragment UI.
4. Fire `nextSlide()`.
5. material-intro will now check your navigation policy again. That should now return `true` because the *registered*-flag is now set.
6. The intro will show the next page.

No guarantee this will work but it should give you an idea on how to achieve that.

**Comment by daniel-stoneuk** [comment]
https://gist.github.com/daniel-stoneuk/18d9d13fe539ce519420093d1768d5ce

This is my implementation.

**Comment by odin-** [comment]
I think it would be good design if each fragment could implement onNavigationBlocked also. I.e. so I don't have to "glue" everything together via the top activity (extended from IntroActivity).

Would that make sense? I could try to implement this depending on what you think Heinrich.

**Comment by odin-** [comment]
OK I did like this. Perhaps not very beautiful but it works (in my fragment):

        ((IntroActivity)getActivity()).addOnNavigationBlockedListener(this);

**Comment by HeinrichReimer** [comment]
Yeah that could be added to `SlideFragment`. Would you mind creating a quick PR?
