### ISSUE TITLE
How CAn I Star new activity when click finish button or last slide

### ISSUE THREAD

**Issue by Spiderbezno** [HeinrichReimer/material-intro#28]
How Can I Star new activity when I click finish button or last slide

**Comment by Maxr1998** [comment]
Override finish() and call startActivity() from there.

**Comment by Spiderbezno** [comment]
Thx, I true, I hadn't thought in this option
Override finish() and call startActivity() from there.

---

**Comment by HeinrichReimer** [comment]
Hey @Spiderbenzo, look at the example. There's sample code on how to open a new activity while having the fancy fade effect on the last page. Take a look at [`FinishActivity`](https://github.com/HeinrichReimer/material-intro/blob/master/app/src/main/java/com/heinrichreimersoftware/materialintro/demo/FinishActivity.java) for more information.
Also feel free to ask here if you run into problems.

**Comment by Spiderbezno** [comment]
I can't see in the eample who call the FinishActivity??

**Comment by daniel-stoneuk** [comment]
Unfortunately, pressing back during the IntroActivity will take you to the activity which you want to display after the intro. I've added some code to `onBackPressed` which takes you to the home screen instead of the previous activity (or in this case, the next activity). I know this isn't ideal behaviour as it should back out into the previous app if launched from an intent - maybe you could try starting a new activity with a flag to clear the stack and then immediately calling `finish()` on that activity.

`@Override`

    public void onBackPressed() {

        Intent startMain = new Intent(Intent.ACTION_MAIN);

        startMain.addCategory(Intent.CATEGORY_HOME);

        startMain.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

        startActivity(startMain);
    }

**Comment by HeinrichReimer** [comment]
@daniel-stoneuk I'll look at this tomorrow

**Comment by HeinrichReimer** [comment]
Possibly fixed by #36 if you listen for the `Intent` result

**Comment by trikhatarun** [comment]
Although using finish() works but it breaks the flow and for a moment the app is closed and then the next activity opens. The flow is not continuous.
