### ISSUE TITLE
Use CoordinatorLayout instead of FrameLayout for Material powa

### ISSUE THREAD

**Issue by DomenicoCasillo** [HeinrichReimer/material-intro#49]
In /res/layout/activity_intro.xml the library uses a FrameLayout as main element. However this prevents us from achieving all the Material's goodness. For example as in your demo app, when showing a Snackbar the Fabs and the InkIndicator doesn't move with the Snackbar, and they get behind it.
Would it be possible to use a CoordinatorLayout instead of a FrameLayout to achive such advantages?

Thanks.

**Comment by HeinrichReimer** [comment]
They are not FABs (That would be completely against the guidelines :laughing:) just image buttons.
I decided to not move the controls up because they are on the main surface, the same as the text and image. If they get moved up, they'd cover the image or text and destroy the material metaphor.
And of course using `CoordinatorLayout` everywhere just because it helps acheiving material effects can have a bad impact on app performance. `FrameLayout` in most cases is the fastest layout you can use on Android.
