### ISSUE TITLE
Custom Slide Fragment "jumps" down after previous slide

### ISSUE THREAD

**Issue by addrum** [HeinrichReimer/material-intro#89]
Not sure if it's my view but swiping to a custom slide fragment makes the whole view "jump" down. This only happens when going left to right, but not right to left (i.e. going from slide **before** custom fragment but coming backwards). See attached video

https://gfycat.com/KindEagerHind

**Comment by HeinrichReimer** [comment]
Good catch!
This is probably a bug with the CTA button's behavior. When it is hidden there's more space and the slide `Fragment` adapts its height in order to fill the additional space.
I'll try to fix that by applying a short anim,ation to the height change. The `Fragment` would adapt it's height more smoothly then.
