### ISSUE TITLE
Is there an onLastButtonPressed?

### ISSUE THREAD

**Issue by addrum** [HeinrichReimer/material-intro#94]
I'd only like to write the preference that it's first launch when the final button is pressed else I get permissions from other parts of the code popping up over the top of the intro which looks messy. Is there a suitable method for this? I've tried following the Splash and FinalActivity examples but I still run into the same issue as it writes the preference immediately after launching.

**Comment by HeinrichReimer** [comment]
No there isn't a callback for this. This is due to the fade effect at the end of the intro.
If you want to store a preference only when the intro has finished correctly you could use `startActivityForResult()`. `IntroActivity` returns `RESULT_OK` only when it is finished correctly and will return `RESULT_CANCELED` otherwise.

*Check the [Android documentation](https://developer.android.com/training/basics/intents/result.html) for further information.*

**Comment by addrum** [comment]
Cheers!
